---
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - 8084:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - /opt/nifi:/opt/nifi/nifi-current
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=nifi
      - flame.url=http://${HOSTNAME}:8084/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=apache # https://pictogrammers.com/library/mdi/
networks:
  default:
    external: true
    name: main-network
