# https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker
---
services:
  asf:
    image: justarchi/archisteamfarm:latest
    container_name: asf
    ports:
      - 1242:1242
    volumes:
      - /opt/asf/config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=asf
      - flame.url=http://${HOST}:1242/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=steam # https://pictogrammers.com/library/mdi/
networks:
  default:
    external: true
    name: main-network
