# https://github.com/amir20/dozzle
---
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8082:8080
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=dozzle
      - flame.url=http://${HOST}:8082/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=math-log # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
