# https://github.com/pawelmalak/flame
# https://github.com/squidfunk/mkdocs-material
# https://www.tecmint.com/shellinabox-web-based-ssh-linux-terminal/
---
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - PASSWORD=${FLAME_PASS}
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=flame dashboard;nifi #;proxmox;shell in a box;docs;netdata;webmin;pterodactyl #;torqueserver documents;shell in a box;torqueserver;proxmox;dir
      - flame.url=http://${HOST}:5005/;http://${HOST}:9080 #;https://docs.${DOMAIN}/;https://sh.${DOMAIN}/;https://${DOMAIN}/;https://proxmox.${DOMAIN}/;https://dir.${DOMAIN}/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=fire-circle;chart-bar #;server-network;ssh;file-document-multiple-outline;chart-bar;server;gamepad #;file-document-multiple-outline;ssh;server-network;file-tree # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
volumes:
  flame-data:
    external: true
