# https://hub.docker.com/r/linuxserver/jackett
---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /opt/jackett/config:/config
      - ${DISK0}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=jackett
      - flame.url=http://${HOSTNAME}:9117/ # or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=tshirt-crew # https://materialdesignicons.com/
      # - homepage.group=Indexing & Search # homepage label https://github.com/benphelps/homepage
      # - homepage.name=jackett
      # - homepage.icon=jackett.png # https://gethomepage.dev/en/configs/services/#icons
      # - homepage.href=http://${HOSTNAME}:9117/
      # - homepage.description=
networks:
  default:
    external: true
    name: main-network
