---
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    # ports:
      # - 9190:9190
      # - 8443:8443 # optional for HTTPS
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      # - NIFI_WEB_HTTP_PORT=9190
      - NIFI_WEB_HTTPS_PORT=8443
      # - NIFI_WEB_HTTPS_HOST=0.0.0.0
      # - NIFI_SECURITY_KEYSTORE=
      # - NIFI_SECURITY_KEYSTOREPASSWD=
      # - NIFI_SECURITY_KEYPASSWD=
      # - NIFI_SECURITY_TRUSTSTORE=
      # - NIFI_SECURITY_TRUSTSTOREPASSWD=
    # volumes:
      - /opt/nifi/keys:/opt/nifi/nifi-current/keys
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=nifi
      - flame.url=https://nifi.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=water # https://pictogrammers.com/library/mdi/
networks:
  default:
    external: true
    name: main-network
