# https://github.com/linuxserver/docker-swag
# https://docs.linuxserver.io/general/swag
---
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - URL=${DOMAIN}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      # - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION=60
      # - DUCKDNSTOKEN= #optional
      - EMAIL=${ADMIN_EMAIL} #optional
      - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS=
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:swag-dashboard
    volumes:
      - /opt/swag/config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=swag
      - flame.url=https://dashboard.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=view-dashboard # https://materialdesignicons.com/
    ports:
      - 443:443
      - 80:80 #optional
      # - 81:81
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
networks:
  default:
    external: true
    name: main-network
