# https://hub.docker.com/r/linuxserver/webtop
---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-openbox-e6f0d5d2-ls102
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
      - DRINODE=/dev/dri/renderD128
      - CUSTOM_USER=${WEBTOP_USER}
      - PASSWORD=${WEBTOP_PASS}
      - DOCKER_MODS=linuxserver/mods:universal-package-install 
      - INSTALL_PACKAGES=${INSTALL_PACKAGES}
    volumes:
      - /opt/webtop/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3330:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true # watchtower auto-update
      - flame.type=app # flame label https://github.com/pawelmalak/flame
      - flame.name=webtop
      - flame.url=https://webtop.${DOMAIN}/ # local http://${HOSTNAME}:80/ or subdomain https://app_name.${DOMAIN}/ or subfolder https://${DOMAIN}/app_name
      - flame.icon=linux # https://materialdesignicons.com/
networks:
  default:
    external: true
    name: main-network
